test('first test', () => {

})

test('fail test', () => {
  throw new Error('Failure')
})